Juggernaut: 
  path: "https://huggingface.co/RunDiffusion/Juggernaut-XL-v9/blob/main/Juggernaut-XL_v9_RunDiffusionPhoto_v2.safetensors"
  single_files: true   ### if true, is a civitai model
  use_safetensors: true

RealVision:
  path: "SG161222/RealVisXL_V4.0"
  single_files: false
  use_safetensors: true

SDXL:
  path: "stabilityai/stable-diffusion-xl-base-1.0"
  single_files: false
  use_safetensors: true

Unstable:
  path: "stablediffusionapi/sdxl-unstable-diffusers-y"
  single_files: false
  use_safetensors: false
